# Generated by Django 5.0.2 on 2024-02-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='img',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
