# Generated by Django 5.0.2 on 2024-02-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=200)),
                ('card_number', models.IntegerField()),
                ('owner_name', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=5)),
                ('cvv', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
    ]
