# Generated by Django 5.0.2 on 2024-02-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0005_alter_card_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crossover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('month_price', models.IntegerField()),
                ('img', models.ImageField(upload_to='photos')),
            ],
            options={
                'verbose_name': 'Crossover',
                'verbose_name_plural': 'Crossovers',
            },
        ),
        migrations.CreateModel(
            name='Electrified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('month_price', models.IntegerField()),
                ('img', models.ImageField(upload_to='photos')),
            ],
            options={
                'verbose_name': 'Electrified',
                'verbose_name_plural': 'Electrifieds',
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('month_price', models.IntegerField()),
                ('img', models.ImageField(upload_to='photos')),
            ],
            options={
                'verbose_name': 'Truck',
                'verbose_name_plural': 'Trucks',
            },
        ),
    ]
